export const Images = {
	bobaAd1: require('@/assets/images/bobaAd1.jpg'),
	bobaAd2: require('@/assets/images/bobaAd2.jpg'),
	boba1: require('../assets/images/DrinkSelection.png'),
	YifangFruitTea: require('../assets/images/YifangFruitTea.png'),
	MangoPomeloSago: require('../assets/images/MangoPomeloSago.png'),
	BrownSugarPearlOolongTeaLatte: require('../assets/images/BrownSugarPearlOolongTeaLatte.png'),
	GrapefruitLemonFruitTea: require('../assets/images/GrapefruitLemonFruitTea.png'),
	PineappleGreenTea: require('../assets/images/PineappleGreenTea.png'),
	YakultwithPassionFruitGreenTea: require('../assets/images/YakultwithPassionFruitGreenTea.png'),
	SweetTaroSagoLatte: require('../assets/images/SweetTaroSagoLatte.png'),
	TarowithMilk: require('../assets/images/TarowithMilk.png'),
	Abloh: require('../assets/images/Abloh.png'),
	Nigo: require('../assets/images/Nigo.png'),
	Takahashi: require('../assets/images/Takahashi.png'),
	Monogram: require('../assets/images/Monogram.png'),
	Heart: require('../assets/images/Heart.png'),
	Yellow: require('../assets/images/Yellow.png'),
	Flower: require('../assets/images/Flower.png'),
	Lover: require('../assets/images/Lover.png'),
};
